In [55]:
import numpy as np
import pandas as pd

In [56]:
df = pd.read_csv('../datasets/cars.csv')

In [57]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [58]:
df['brand'].value_counts()

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Force               6
Land                6
Isuzu               5
Kia                 4
Ambassador          4
Daewoo              3
MG                  3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [59]:
df['brand'].nunique()

32

In [60]:
df['fuel'].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

### Applying one hot encoding using Pandas

In [61]:
# This will remove the original column and add new column according the one hot encoding process
# This will remove the multillinearity problem by itself
pd.get_dummies(df,columns=['fuel','owner'])

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,False,True,False,False,True,False,False,False,False
1,Skoda,120000,370000,False,True,False,False,False,False,True,False,False
2,Honda,140000,158000,False,False,False,True,False,False,False,False,True
3,Hyundai,127000,225000,False,True,False,False,True,False,False,False,False
4,Maruti,120000,130000,False,False,False,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,False,True,True,False,False,False,False
8124,Hyundai,119000,135000,False,True,False,False,False,True,False,False,False
8125,Maruti,120000,382000,False,True,False,False,True,False,False,False,False
8126,Tata,25000,290000,False,True,False,False,True,False,False,False,False
8127,Tata,25000,290000,False,True,False,False,True,False,False,False,False

In [62]:
# Remoding the problem of multilinearity
pd.get_dummies(df,columns=['fuel','owner'],drop_first=True)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,False

### Applying one hot encoding using sklearn library

In [63]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [64]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(df.iloc[:,0:4],df.iloc[:,4:],test_size=0.3,random_state=42)

In [65]:
x_train

         brand  km_driven    fuel         owner
6783    Maruti     120000  Petrol   Third Owner
1073    Toyota     100000  Diesel   First Owner
7756       BMW      39000  Diesel   First Owner
144     Toyota      39000  Petrol   First Owner
6424    Maruti      70000  Diesel  Second Owner
...        ...        ...     ...           ...
5226  Mahindra     120000  Diesel   First Owner
5390    Maruti      80000  Diesel  Second Owner
860    Hyundai      35000  Petrol   First Owner
7603    Maruti      27000  Diesel   First Owner
7270    Maruti      70000  Petrol  Second Owner

[5689 rows x 4 columns]

In [66]:
x_test

        brand  km_driven    fuel         owner
1971    Honda     110000  Petrol   Third Owner
4664     Tata     291977  Diesel   First Owner
5448   Maruti      70000  Diesel   First Owner
3333    Honda     120000  Petrol  Second Owner
2316   Maruti      69000  Diesel  Second Owner
...       ...        ...     ...           ...
462   Hyundai      35000  Petrol   First Owner
1956   Toyota      90000  Diesel   Third Owner
3782   Maruti      20000  Petrol   First Owner
799   Renault      60000  Petrol   First Owner
2402   Toyota     270000  Diesel   Third Owner

[2439 rows x 4 columns]

In [67]:
y_train

      selling_price
6783         110000
1073        2940000
7756        2950000
144          625000
6424         395000
...             ...
5226         475000
5390         530000
860          576000
7603         770000
7270         155000

[5689 rows x 1 columns]

In [68]:
y_test

      selling_price
1971         198000
4664         500000
5448         425000
3333         150000
2316         525000
...             ...
462          600000
1956         400000
3782         500000
799          400000
2402         425000

[2439 rows x 1 columns]

In [69]:
from sklearn.preprocessing import OneHotEncoder

In [70]:
ohe = OneHotEncoder(drop='first')

In [71]:
# Creating sparse matrix for fuel and owner for encoding process
x_train_new = ohe.fit_transform(x_train[['fuel','owner']]).toarray()

In [72]:
x_test_new = ohe.fit_transform(x_test[['fuel','owner']]).toarray()

In [73]:
x_train_new

array([[0., 0., 1., ..., 0., 0., 1.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 1., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 1., 0., 0.]], shape=(5689, 7))

In [74]:
x_test_new

array([[0., 0., 1., ..., 0., 0., 1.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 1.]], shape=(2439, 7))

In [75]:
np.hstack((x_train[['brand','km_driven']].values,x_train_new))

array([['Maruti', 120000, 0.0, ..., 0.0, 0.0, 1.0],
       ['Toyota', 100000, 1.0, ..., 0.0, 0.0, 0.0],
       ['BMW', 39000, 1.0, ..., 0.0, 0.0, 0.0],
       ...,
       ['Hyundai', 35000, 0.0, ..., 0.0, 0.0, 0.0],
       ['Maruti', 27000, 1.0, ..., 0.0, 0.0, 0.0],
       ['Maruti', 70000, 0.0, ..., 1.0, 0.0, 0.0]],
      shape=(5689, 9), dtype=object)

In [76]:
np.hstack((x_train[['brand','km_driven']].values,x_train_new)).shape

(5689, 9)

In [77]:
# Note : for removing the multilinearity we can use ohe = OneHotEncoder(drop='first') -> IT will remove the multilinearity 
#problem automatically

### One Hot Encoding with multiple categories

In [78]:
# Calculating the number of different vechiles
count = df['brand'].value_counts()

In [79]:
count

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Force               6
Land                6
Isuzu               5
Kia                 4
Ambassador          4
Daewoo              3
MG                  3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [81]:
df['brand'].nunique()
threshold = 100

In [84]:
# finding the index of the brand whose value is less than 100
repl = count[count<=threshold].index

In [85]:
repl

Index(['Nissan', 'Jaguar', 'Volvo', 'Datsun', 'Mercedes-Benz', 'Fiat', 'Audi',
       'Lexus', 'Jeep', 'Mitsubishi', 'Force', 'Land', 'Isuzu', 'Kia',
       'Ambassador', 'Daewoo', 'MG', 'Ashok', 'Opel', 'Peugeot'],
      dtype='object', name='brand')

In [87]:
pd.get_dummies(df['brand'].replace(repl,'uncommon'))

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
0,False,False,False,False,False,False,True,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,True,False,False,False,False
2,False,False,False,True,False,False,False,False,False,False,False,False,False
3,False,False,False,False,True,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8123,False,False,False,False,True,False,False,False,False,False,False,False,False
8124,False,False,False,False,True,False,False,False,False,False,False,False,False
8125,False,False,False,False,False,False,True,False,False,False,False,False,False
8126,False,False,False,False,False,False,False,False,False,True,False,False,False
8127,False,False,False,False,False,False,False,False,False,True,False,False,False

In [88]:
df.shape[0]

8128