# Multivariare Imputation -> KNN Imputer

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.impute import KNNImputer, SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [4]:
data = pd.read_csv('../../datasets/train 2.csv')

In [5]:
data.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [7]:
data = data[['Age','Pclass','Fare','Survived']]

In [8]:
data.head()

    Age  Pclass     Fare  Survived
0  22.0       3   7.2500         0
1  38.0       1  71.2833         1
2  26.0       3   7.9250         1
3  35.0       1  53.1000         1
4  35.0       3   8.0500         0

In [11]:
data.isnull().mean()*100

Age         19.86532
Pclass       0.00000
Fare         0.00000
Survived     0.00000
dtype: float64

In [12]:
x = data.drop(columns=['Survived'])
y = data['Survived']

In [16]:
x.head()

    Age  Pclass     Fare
0  22.0       3   7.2500
1  38.0       1  71.2833
2  26.0       3   7.9250
3  35.0       1  53.1000
4  35.0       3   8.0500

In [17]:
y.head()

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

In [18]:
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state=42,test_size=0.3)

In [19]:
x_train.shape

(623, 3)

Apply KNNImputer

In [20]:
knn = KNNImputer()
x_train_trf = knn.fit_transform(x_train)
x_test_trf = knn.transform(x_test)

In [22]:
x_train.isnull().sum()

Age       124
Pclass      0
Fare        0
dtype: int64

In [24]:
lr  = LogisticRegression()
lr.fit(x_train_trf,y_train)
y_pred = lr.predict(x_test_trf)
accuracy_score(y_pred,y_test)

0.7238805970149254

## Comparision with SimpleImputer

In [26]:
si = SimpleImputer()
x_train_trf2 = si.fit_transform(x_train)
x_test_trf2 = si.transform(x_test)

In [27]:
lr = LogisticRegression()
lr.fit(x_train_trf2,y_train)
y_pred2 = lr.predict(x_test_trf2)
accuracy_score(y_test,y_pred)

0.7238805970149254