# Encoding Numerical features

In [1]:
import pandas as pd
import numpy as np

In [5]:
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split

from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import accuracy_score  # used for checking accuracy of the prection model
from sklearn.model_selection import cross_val_score  

from sklearn.preprocessing import KBinsDiscretizer  # importing descretization
from sklearn.compose import ColumnTransformer  # column transformer is just like as pipeline that is uses for applying transformation over multiple column at the single time

In [7]:
data = pd.read_csv('../../datasets/titanic2.csv',usecols=['Age','Fare','Survived'])

In [8]:
data.head(3)

   Survived   Age    Fare
0         0  34.5  7.8292
1         1  47.0  7.0000
2         0  62.0  9.6875

In [9]:
data.isnull().sum()

Survived     0
Age         86
Fare         1
dtype: int64

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  418 non-null    int64
 1   Age       332 non-null    float64
 2   Fare      417 non-null    float64
dtypes: float64(2), int64(1)
memory usage: 9.9 KB

In [11]:
data.shape

(418, 3)

In [12]:
# dropping the null values 
data.dropna(inplace=True)

In [13]:
data.isnull().sum()

Survived    0
Age         0
Fare        0
dtype: int64

In [14]:
data.shape

(331, 3)

In [15]:
data.head(1)

   Survived   Age    Fare
0         0  34.5  7.8292

In [16]:
x = data.iloc[:,1:]

In [17]:
x

      Age      Fare
0    34.5    7.8292
1    47.0    7.0000
2    62.0    9.6875
3    27.0    8.6625
4    22.0   12.2875
..    ...       ...
409   3.0   13.7750
411  37.0   90.0000
412  28.0    7.7750
414  39.0  108.9000
415  38.5    7.2500

[331 rows x 2 columns]

In [18]:
y = data.iloc[:,0:1]

In [19]:
y.head(3)

   Survived
0         0
1         1
2         0

In [22]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=42)

In [23]:
# DecisionTreeClassifier object
clf = DecisionTreeClassifier()

In [24]:
# learning parameter for prediction 
clf.fit(x_train,y_train)
y_pred = clf.predict(x_test)

In [25]:
# accuracy score
accuracy_score(y_pred,y_test)

0.6

In [28]:
# cross val is used for cheking prediction multiple times
np.mean(cross_val_score(clf,x,y,cv=10,scoring='accuracy')) # It predict the actual prediction

np.float64(0.5649732620320856)

In [36]:
# creating kbins_objects
kbin_age = KBinsDiscretizer(n_bins=10,encode='ordinal',strategy='quantile')
kbin_fare = KBinsDiscretizer(n_bins=10,encode='ordinal',strategy='quantile')

ColumnTransformer : Apply different transformer to different columns all in one step

In [37]:
trf = ColumnTransformer([
    ('first',kbin_age,[0]), # (name,kbindiscretiser object,index)
    ('second',kbin_fare,[1])
])

Tuple 1 — ('first', kbin_age, [0])

'first' → just a name you give this step (can be anything)
kbin_age → the KBinsDiscretizer object you created for age
[0] → apply this to column index 0 (which is your age column)

In [38]:
# converting the x_train and x_test into quantile form
x_train_trf = trf.fit_transform(x_train)
x_test_trf = trf.fit_transform(x_test)

C:\Users\dspri\anaconda3\Lib\site-packages\sklearn\preprocessing\_discretization.py:304: FutureWarning: The current default behavior, quantile_method='linear', will be changed to quantile_method='averaged_inverted_cdf' in scikit-learn version 1.9 to naturally support sample weight equivalence properties by default. Pass quantile_method='averaged_inverted_cdf' explicitly to silence this warning.
  warnings.warn(
C:\Users\dspri\anaconda3\Lib\site-packages\sklearn\preprocessing\_discretization.py:304: FutureWarning: The current default behavior, quantile_method='linear', will be changed to quantile_method='averaged_inverted_cdf' in scikit-learn version 1.9 to naturally support sample weight equivalence properties by default. Pass quantile_method='averaged_inverted_cdf' explicitly to silence this warning.
  warnings.warn(
C:\Users\dspri\anaconda3\Lib\site-packages\sklearn\preprocessing\_discretization.py:304: FutureWarning: The current default behavior, quantile_method='linear', will be changed to quantile_method='averaged_inverted_cdf' in scikit-learn version 1.9 to naturally support sample weight equivalence properties by default. Pass quantile_method='averaged_inverted_cdf' explicitly to silence this warning.
  warnings.warn(
C:\Users\dspri\anaconda3\Lib\site-packages\sklearn\preprocessing\_discretization.py:304: FutureWarning: The current default behavior, quantile_method='linear', will be changed to quantile_method='averaged_inverted_cdf' in scikit-learn version 1.9 to naturally support sample weight equivalence properties by default. Pass quantile_method='averaged_inverted_cdf' explicitly to silence this warning.
  warnings.warn(

In [42]:
x_train_trf

array([[8., 9.],
       [5., 4.],
       [5., 9.],
       [8., 7.],
       [9., 9.],
       [8., 6.],
       [4., 4.],
       [6., 0.],
       [6., 2.],
       [9., 3.],
       [8., 6.],
       [5., 1.],
       [6., 2.],
       [6., 1.],
       [1., 8.],
       [3., 3.],
       [5., 9.],
       [7., 8.],
       [5., 4.],
       [5., 5.],
       [8., 0.],
       [8., 9.],
       [8., 3.],
       [1., 7.],
       [9., 8.],
       [6., 5.],
       [9., 9.],
       [5., 2.],
       [9., 9.],
       [1., 4.],
       [5., 6.],
       [0., 4.],
       [1., 8.],
       [0., 4.],
       [9., 4.],
       [8., 7.],
       [2., 7.],
       [3., 1.],
       [8., 8.],
       [7., 8.],
       [3., 1.],
       [9., 9.],
       [4., 5.],
       [9., 6.],
       [0., 4.],
       [9., 7.],
       [2., 5.],
       [4., 1.],
       [5., 6.],
       [0., 4.],
       [1., 1.],
       [6., 2.],
       [4., 4.],
       [4., 2.],
       [1., 2.],
       [7., 9.],
       [6., 1.],
       [0., 7.],
       [1., 2.],
       [5., 5.],
       [2., 1.],
       [7., 5.],
       [0., 7.],
       [2., 6.],
       [0., 3.],
       [0., 7.],
       [1., 2.],
       [9., 2.],
       [4., 6.],
       [3., 8.],
       [5., 3.],
       [3., 8.],
       [3., 0.],
       [4., 7.],
       [4., 4.],
       [2., 4.],
       [6., 5.],
       [4., 6.],
       [8., 8.],
       [3., 1.],
       [6., 4.],
       [1., 4.],
       [1., 7.],
       [4., 2.],
       [1., 5.],
       [9., 4.],
       [9., 5.],
       [0., 2.],
       [0., 2.],
       [1., 1.],
       [8., 6.],
       [0., 4.],
       [9., 6.],
       [7., 1.],
       [3., 7.],
       [7., 1.],
       [9., 8.],
       [0., 7.],
       [4., 5.],
       [3., 0.],
       [6., 4.],
       [6., 8.],
       [4., 0.],
       [9., 6.],
       [3., 0.],
       [6., 4.],
       [7., 4.],
       [2., 4.],
       [6., 5.],
       [3., 4.],
       [7., 6.],
       [3., 3.],
       [6., 7.],
       [5., 4.],
       [6., 1.],
       [2., 2.],
       [3., 7.],
       [4., 1.],
       [1., 5.],
       [8., 6.],
       [5., 5.],
       [2., 3.],
       [4., 9.],
       [3., 2.],
       [7., 7.],
       [6., 7.],
       [5., 4.],
       [4., 2.],
       [5., 2.],
       [7., 4.],
       [6., 2.],
       [2., 3.],
       [5., 5.],
       [3., 8.],
       [7., 8.],
       [4., 9.],
       [8., 9.],
       [9., 6.],
       [7., 6.],
       [5., 7.],
       [7., 5.],
       [2., 3.],
       [0., 7.],
       [2., 2.],
       [9., 9.],
       [4., 3.],
       [9., 7.],
       [0., 8.],
       [7., 1.],
       [0., 7.],
       [4., 6.],
       [4., 3.],
       [4., 0.],
       [2., 1.],
       [0., 4.],
       [1., 7.],
       [1., 0.],
       [6., 9.],
       [3., 6.],
       [0., 9.],
       [9., 8.],
       [3., 1.],
       [7., 0.],
       [7., 6.],
       [2., 7.],
       [5., 9.],
       [2., 1.],
       [8., 8.],
       [1., 5.],
       [4., 4.],
       [7., 6.],
       [3., 8.],
       [9., 9.],
       [3., 2.],
       [0., 6.],
       [4., 4.],
       [5., 5.],
       [8., 8.],
       [8., 7.],
       [9., 6.],
       [2., 0.],
       [8., 0.],
       [6., 9.],
       [1., 1.],
       [2., 1.],
       [7., 4.],
       [5., 6.],
       [1., 0.],
       [1., 1.],
       [6., 4.],
       [2., 0.],
       [8., 8.],
       [1., 4.],
       [3., 4.],
       [4., 2.],
       [9., 9.],
       [2., 2.],
       [5., 9.],
       [9., 9.],
       [0., 9.],
       [1., 2.],
       [5., 4.],
       [1., 4.],
       [7., 8.],
       [9., 8.],
       [9., 6.],
       [9., 9.],
       [4., 0.],
       [9., 6.],
       [6., 6.],
       [2., 8.],
       [8., 9.],
       [4., 3.],
       [9., 6.],
       [8., 0.],
       [5., 6.],
       [3., 8.],
       [1., 2.],
       [7., 4.],
       [6., 6.],
       [4., 0.],
       [2., 1.],
       [1., 6.],
       [6., 3.],
       [7., 0.],
       [0., 0.],
       [1., 0.],
       [4., 1.],
       [7., 2.],
       [0., 0.],
       [7., 4.]])

In [43]:
x_test_trf

array([[3., 0.],
       [0., 5.],
       [0., 5.],
       [3., 3.],
       [6., 6.],
       [4., 3.],
       [0., 5.],
       [6., 2.],
       [4., 7.],
       [8., 7.],
       [5., 7.],
       [2., 5.],
       [6., 1.],
       [8., 6.],
       [1., 3.],
       [9., 7.],
       [9., 9.],
       [5., 9.],
       [4., 6.],
       [0., 6.],
       [5., 4.],
       [8., 6.],
       [0., 4.],
       [8., 7.],
       [1., 3.],
       [3., 2.],
       [9., 8.],
       [0., 7.],
       [1., 1.],
       [3., 8.],
       [8., 4.],
       [9., 7.],
       [7., 9.],
       [5., 1.],
       [0., 5.],
       [2., 0.],
       [8., 4.],
       [5., 1.],
       [0., 6.],
       [3., 2.],
       [4., 3.],
       [4., 8.],
       [3., 5.],
       [3., 1.],
       [7., 9.],
       [1., 2.],
       [3., 3.],
       [6., 9.],
       [3., 1.],
       [1., 5.],
       [0., 5.],
       [6., 0.],
       [7., 3.],
       [2., 0.],
       [5., 0.],
       [7., 1.],
       [5., 6.],
       [1., 2.],
       [8., 5.],
       [2., 1.],
       [9., 9.],
       [2., 3.],
       [9., 9.],
       [5., 3.],
       [4., 1.],
       [9., 9.],
       [2., 2.],
       [0., 4.],
       [9., 8.],
       [7., 0.],
       [5., 2.],
       [3., 8.],
       [2., 3.],
       [2., 4.],
       [4., 3.],
       [2., 2.],
       [8., 8.],
       [8., 7.],
       [6., 4.],
       [7., 0.],
       [8., 6.],
       [9., 8.],
       [6., 5.],
       [7., 7.],
       [1., 8.],
       [8., 9.],
       [2., 0.],
       [9., 9.],
       [1., 8.],
       [7., 6.],
       [8., 4.],
       [6., 1.],
       [1., 7.],
       [4., 1.],
       [6., 6.],
       [7., 4.],
       [6., 0.],
       [5., 3.],
       [1., 4.],
       [6., 8.]])