# Handling missing values by classifying it is missing or not

In [ ]:
// DOUBT

In [133]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [134]:
data = pd.read_csv('../../datasets/titanic_toy.csv')

In [135]:
data.head(4)

    Age     Fare  Family  Survived
0  22.0   7.2500       1         0
1  38.0  71.2833       1         1
2  26.0   7.9250       0         1
3  35.0  53.1000       1         1

In [136]:
x = data.drop(columns=['Survived','Family'])
y = data['Survived']

In [137]:
x.head(5)

    Age     Fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500

In [138]:
y.head(5)

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

In [139]:
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state=42,test_size=42)

In [140]:
x_train.shape

(849, 2)

In [141]:
x_test.shape

(42, 2)

Prediction before imputation

In [142]:
from sklearn.impute import MissingIndicator,SimpleImputer

In [143]:
si = SimpleImputer()
x_train_trf = si.fit_transform(x_train)
x_test_trf = si.fit_transform(x_test)

In [144]:
x_train_trf

array([[ 29.91361233,   8.05      ],
       [ 29.91361233,   7.75      ],
       [ 45.        ,  14.4542    ],
       ...,
       [ 41.        ,  32.82442472],
       [ 14.        , 120.        ],
       [ 21.        ,  77.2875    ]], shape=(849, 2))

In [145]:
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression()
clf.fit(x_train_trf,y_train)
y_pred = clf.predict(x_test_trf)

from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.5714285714285714

In [146]:
mi = MissingIndicator()

In [147]:
mi.fit(x_train)

MissingIndicator()

In [148]:
x_train.head(5)

      Age     Fare
837   NaN   8.0500
790   NaN   7.7500
362  45.0  14.4542
86   16.0  34.3750
67   19.0   8.1583

In [152]:
x_train.shape

(849, 2)

In [150]:
x_train_missing = si.fit_transform(x_train.iloc[:, 0:1])

In [131]:
x_train_missing

array([[ True, False],
       [ True, False],
       [False, False],
       ...,
       [False,  True],
       [False, False],
       [False, False]], shape=(849, 2))

In [96]:
x_test_missing = mi.transform(x_test)

In [97]:
x_test_missing

array([[ True, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [False,  True],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [ True, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False]])

In [98]:
x_train.head(3)

      Age     Fare
837   NaN   8.0500
790   NaN   7.7500
362  45.0  14.4542

In [ ]:
//DOUBT

In [102]:
x_test['Age_NA'] = x_test_missing

ValueError: Expected a 1D array, got an array with shape (42, 2)

# Performing all above operations using sklearn library

In [112]:
si = SimpleImputer(add_indicator=True)
x_train_trf2 = si.fit_transform(x_train)
x_test_trf2 si.fit_transform(x_test)

SyntaxError: invalid syntax (1616769946.py, line 3)

In [110]:
x_train = si.fit_transform(x_train)

In [111]:
x_test = si.fit_transform(x_test)

In [ ]:
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression()
clf.fit(clf)