# Binarization

In [69]:
import pandas as pd
import numpy as np

In [70]:
# During importing data drop unnessary columns
data = pd.read_csv('../../datasets/titanic2.csv')[['Survived','Fare','SibSp','Parch','Age']]

In [71]:
data.head(3)

   Survived    Fare  SibSp  Parch   Age
0         0  7.8292      0      0  34.5
1         1  7.0000      1      0  47.0
2         0  9.6875      0      0  62.0

In [72]:
# creating a new column name family by combing columns SibSp and Parch
data['Family'] = data['Parch'] + data['SibSp']

In [73]:
data.head(3)

   Survived    Fare  SibSp  Parch   Age  Family
0         0  7.8292      0      0  34.5       0
1         1  7.0000      1      0  47.0       1
2         0  9.6875      0      0  62.0       0

In [74]:
data.dropna(inplace=True)

In [75]:
data.isnull().sum()

Survived    0
Fare        0
SibSp       0
Parch       0
Age         0
Family      0
dtype: int64

In [76]:
# Dropping Sibsp and Parch columns
data = data.drop(columns=['SibSp','Parch'])

In [77]:
data.head(3)

   Survived    Fare   Age  Family
0         0  7.8292  34.5       0
1         1  7.0000  47.0       1
2         0  9.6875  62.0       0

In [78]:
data.isnull().sum()

Survived    0
Fare        0
Age         0
Family      0
dtype: int64

In [79]:
data.head()

   Survived     Fare   Age  Family
0         0   7.8292  34.5       0
1         1   7.0000  47.0       1
2         0   9.6875  62.0       0
3         0   8.6625  27.0       0
4         1  12.2875  22.0       2

In [80]:
x = data.iloc[:,1:]
y= data.iloc[:,0:1]

In [81]:
x.head(2)

     Fare   Age  Family
0  7.8292  34.5       0
1  7.0000  47.0       1

In [82]:
y.head(2)

   Survived
0         0
1         1

In [83]:
# importing train test split
from sklearn.model_selection import train_test_split

In [84]:
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state=42,test_size=0.3)

In [85]:
x_train.head(2)

        Fare   Age  Family
24   262.375  48.0       4
359   15.550  30.0       1

In [86]:
x_train.shape

(231, 3)

In [87]:
y_train.shape

(231, 1)

In [88]:
x_test.shape

(100, 3)

In [89]:
y_test.shape

(100, 1)

In [90]:
data.head(2)

   Survived    Fare   Age  Family
0         0  7.8292  34.5       0
1         1  7.0000  47.0       1

In [91]:
# importing DecisionTreeClassifier -> for prediction
from sklearn.tree import DecisionTreeClassifier
# object of DecisionTreeClassifier
clf = DecisionTreeClassifier()
from sklearn.metrics import accuracy_score

In [92]:
### Prection without applying binarization
clf.fit(x_train,y_train)
y_pred =  clf.predict(x_test)
print('the sccuracy score without applying binarisation is : ',accuracy_score(y_pred,y_test))

the sccuracy score without applying binarisation is :  0.6

In [93]:
from sklearn.model_selection import cross_val_score

In [94]:
# It gives the accuracy of the data after prediction data ten times
np.mean(cross_val_score(DecisionTreeClassifier(),x,y,cv=10,scoring='accuracy'))

np.float64(0.5982174688057041)

# Calculating accuracy score after applying binarization

In [95]:
# binarisation convert the data between 0 and 1
from sklearn.preprocessing import Binarizer

In [96]:
data.head(1)

   Survived    Fare   Age  Family
0         0  7.8292  34.5       0

In [97]:
# importing column transformer
from sklearn.compose import ColumnTransformer

In [98]:
# applying Binarization over family column
trf = ColumnTransformer([
    ('trf',Binarizer(copy=False),['Family']) # copy=False -> It means do not make copy of data just modify inplace data
],remainder='passthrough')

In [99]:
data.head(1)

   Survived    Fare   Age  Family
0         0  7.8292  34.5       0

In [100]:
x_train.head(1)

       Fare   Age  Family
24  262.375  48.0       4

In [102]:
# transforming x_train and  _x_test data using the binarizatiom
x_train_trf = trf.fit_transform(x_train) # fitting is already done here
x_test_trf = trf.fit_transform(x_test)

In [104]:
# Note -> Always be remember after applying the transformation data converted in numpy array

In [108]:
# converting transform data from numpy to dataframe
x_train_trf = pd.DataFrame(x_train_trf,columns=['Family','Age','Fare'])

In [111]:
x_train_trf.head(1)

   Family      Age  Fare
0     1.0  262.375  48.0

In [112]:
# Note -> sklearn do not care which kind of data you are passing dataframe or numpy array during fitting model.

In [114]:
clf.fit(x_train_trf,y_train)
y_pred2 = clf.predict(x_test_trf)
print('The accuracy score of the model after applying the binarization : ',accuracy_score(y_pred2,y_test))

The accuracy score of the model after applying the binarization :  0.6

C:\Users\dspri\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

In [ ]:
//doubt

In [121]:
np.mean(cross_val_score(DecisionTreeClassifier(),x,y,cv=10,scoring='accuracy'))

np.float64(0.598306595365419)