# Handling date and time

In [20]:
import pandas as pd
import numpy as np

In [21]:
date = pd.read_csv('../../datasets/orders.csv')
time = pd.read_csv('../../datasets/messages.csv')

In [22]:
date.head(2)

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157

In [23]:
date.shape

(1000, 4)

In [24]:
time.head(2)

                  date                                               msg
0  2013-12-15 00:50:00                          ищу на сегодня мужика 37
1  2014-04-29 23:40:00  ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826

In [25]:
time.shape

(1000, 2)

In [26]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [27]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

# Note : Initially date and time columns are in object. So we have to convert then into date and time.

# Working With date

In [28]:
# converting date into datetime datatype
date['date'] = pd.to_datetime(date['date'])

In [29]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

In [30]:
date.head()

        date  product_id  city_id  orders
0 2019-12-10        5628       25       3
1 2018-08-15        3646       14     157
2 2018-10-23        1859       25       1
3 2019-08-17        7292       25       1
4 2019-01-06        4344       25       3

In [31]:
# Extracting year - > Making a new column for year
date['year'] = date['date'].dt.year
date.head(2)

        date  product_id  city_id  orders  year
0 2019-12-10        5628       25       3  2019
1 2018-08-15        3646       14     157  2018

In [32]:
# Extracting month
date['month'] = date['date'].dt.month
date.head()

        date  product_id  city_id  orders  year  month
0 2019-12-10        5628       25       3  2019     12
1 2018-08-15        3646       14     157  2018      8
2 2018-10-23        1859       25       1  2018     10
3 2019-08-17        7292       25       1  2019      8
4 2019-01-06        4344       25       3  2019      1

In [33]:
# Extracting date of month
date['month_name'] = date['date'].dt.month_name()
date.head()

        date  product_id  city_id  orders  year  month month_name
0 2019-12-10        5628       25       3  2019     12   December
1 2018-08-15        3646       14     157  2018      8     August
2 2018-10-23        1859       25       1  2018     10    October
3 2019-08-17        7292       25       1  2019      8     August
4 2019-01-06        4344       25       3  2019      1    January

In [35]:
# Extracting month date
date['month_date'] = date['date'].dt.day
date.head()

        date  product_id  city_id  orders  year  month month_name  month_date
0 2019-12-10        5628       25       3  2019     12   December          10
1 2018-08-15        3646       14     157  2018      8     August          15
2 2018-10-23        1859       25       1  2018     10    October          23
3 2019-08-17        7292       25       1  2019      8     August          17
4 2019-01-06        4344       25       3  2019      1    January           6

In [ ]:
// Doubt

In [37]:
# Extracting day of week
date['week'] = date['date'].dt.dayofweek
date.head(20)

,date,product_id,city_id,orders,year,month,month_name,month_date,week
0,2019-12-10,5628,25,3,2019,12,December,10,1
1,2018-08-15,3646,14,157,2018,8,August,15,2
2,2018-10-23,1859,25,1,2018,10,October,23,1
3,2019-08-17,7292,25,1,2019,8,August,17,5
4,2019-01-06,4344,25,3,2019,1,January,6,6
5,2018-08-23,1811,25,4,2018,8,August,23,3
6,2018-11-21,1282,26,1,2018,11,November,21,2
7,2019-03-27,5022,2,41,2019,3,March,27,2
8,2019-06-29,3699,3,15,2019,6,June,29,5
9,2018-08-30,4373,11,3,2018,8,August,30,3
10,2019-10-24,6339,26,1,2019,10,October,24,3
11,2019-08-02,3311,22,6,2019,8,August,2,4
12,2019-03-15,5665,5,1,2019,3,March,15,4
13,2018-08-24,3020,13,4,2018,8,August,24,4
14,2019-05-29,3833,26,240,2019,5,May,29,2
15,2019-02-14,202,2,4,2019,2,February,14,3
16,2019-04-10,977,22,1,2019,4,April,10,2
17,2018-09-24,2701,14,16,2018,9,September,24,0
18,2019-06-12,5630,14,31,2019,6,June,12,2
19,2019-04-13,7163,2,20,2019,4,April,13,5

In [39]:
# Extracting day of that day
date['day'] = date['date'].dt.day_name()
date.head(3)

,date,product_id,city_id,orders,year,month,month_name,month_date,week,day
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday

In [42]:
# dropping unnecessary columns
date.drop(columns=['product_id','city_id','orders']).head()

        date  year  month month_name  month_date  week        day
0 2019-12-10  2019     12   December          10     1    Tuesday
1 2018-08-15  2018      8     August          15     2  Wednesday
2 2018-10-23  2018     10    October          23     1    Tuesday
3 2019-08-17  2019      8     August          17     5   Saturday
4 2019-01-06  2019      1    January           6     6     Sunday

In [44]:
# is Weekend
date['is_weekend'] = np.where(date['day'].isin(['Sunday','Saturday']),1,0)
date.head()

,date,product_id,city_id,orders,year,month,month_name,month_date,week,day,is_weekend
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday,0
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday,0
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday,0
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday,1
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday,1

In [47]:
# Extrating week of year
date['week_year'] = date['date'].dt.isocalendar().week   
date.head()

,date,product_id,city_id,orders,year,month,month_name,month_date,week,day,is_weekend,week_year
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday,0,50
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday,0,33
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday,0,43
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday,1,33
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday,1,1

In [49]:
# Extracting quater
date['quarter'] = date['date'].dt.quarter
date.head()

,date,product_id,city_id,orders,year,month,month_name,month_date,week,day,is_weekend,week_year,quarter
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday,0,50,4
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday,0,33,3
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday,0,43,4
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday,1,33,3
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday,1,1,1

In [ ]:
#extracting the semester
date['semester'] = np.where(date)