In [15]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [16]:
data = pd.read_csv('../../datasets/50_Startups.csv')

In [17]:
data.head()

   R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [18]:
data = data.drop(columns=['State'])

In [19]:
data.head()

   R&D Spend  Administration  Marketing Spend     Profit
0  165349.20       136897.80        471784.10  192261.83
1  162597.70       151377.59        443898.53  191792.06
2  153441.51       101145.55        407934.54  191050.39
3  144372.41       118671.85        383199.62  182901.99
4  142107.34        91391.77        366168.42  166187.94

In [21]:
# creating missing value in data
data.iloc[1,0] = np.nan
data.iloc[3,1] = np.nan
data.iloc[4,3] = np.nan

In [22]:
data.head()

   R&D Spend  Administration  Marketing Spend     Profit
0  165349.20       136897.80        471784.10  192261.83
1        NaN       151377.59        443898.53  191792.06
2  153441.51       101145.55        407934.54  191050.39
3  144372.41             NaN        383199.62  182901.99
4  142107.34        91391.77        366168.42        NaN

In [ ]:
// Continue all these step upto three itrations