# writting lr model by scrach

In [33]:
# defing class
class meralr:
    def __init__(self):
        self.m = None
        self.b = None

    # fit function
    def fit(self,x_train,y_train): # self is used for accessing the variable of another method
        # it is resposible for finding m and b
        num = 0
        den = 0

        for i in range(x_train.shape[0]):
            num  = num  + ( (x_train.iloc[i] - x_train.mean())* (y_train.iloc[i] - y_train.mean()) )
            den = den + ((x_train.iloc[i] - x_train.mean() )*(x_train.iloc[i] - x_train.mean()))

        self.m = num/den
        self.b = y_train.mean() - (self.m*x_train.mean())
        print(self.m)
        print(self.b)

    # predict function
    def predict(self,x_test):
        print(x_test)
        return self.m*x_test + self.b

In [34]:
import numpy as np
import pandas as pd

In [35]:
data = pd.read_csv('../../datasets/placement2.csv')

In [36]:
data.head()

   cgpa  package
0  6.89     3.26
1  5.12     1.98
2  7.82     3.25
3  7.42     3.67
4  6.94     3.57

In [37]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   cgpa     200 non-null    float64
 1   package  200 non-null    float64
dtypes: float64(2)
memory usage: 3.3 KB

In [38]:
x = data[['cgpa']]
y = data['package']

In [39]:
x.shape

(200, 1)

In [40]:
y.shape

(200,)

In [41]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=42)

In [42]:
x.shape

(200, 1)

In [43]:
x_train.shape

(140, 1)

In [44]:
x_test.shape

(60, 1)

In [45]:
x_train.shape

(140, 1)

In [46]:
x_train.shape[0]

140

In [47]:
# defing object
lr = meralr()

In [48]:
lr.fit(x_train,y_train)

cgpa    0.570181
dtype: float64
cgpa   -0.980884
dtype: float64

In [50]:
print(lr.predict(x_test.iloc[0]))

cgpa    6.63
Name: 95, dtype: float64
cgpa    2.799416
dtype: float64

In [51]:
data

     cgpa  package
0    6.89     3.26
1    5.12     1.98
2    7.82     3.25
3    7.42     3.67
4    6.94     3.57
..    ...      ...
195  6.93     2.46
196  5.89     2.57
197  7.21     3.24
198  7.63     3.96
199  6.22     2.33

[200 rows x 2 columns]