# feature construction and feature splitting

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [43]:
data = pd.read_csv('../../datasets/titanic2.csv')

In [7]:
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [8]:
data.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [9]:
data = data[['Age','Pclass','SibSp','Parch','Survived']]

In [10]:
data.head()

    Age  Pclass  SibSp  Parch  Survived
0  34.5       3      0      0         0
1  47.0       3      1      0         1
2  62.0       2      0      0         0
3  27.0       3      0      0         0
4  22.0       3      1      1         1

In [11]:
# dropping missing values
data.dropna(inplace=True)

In [12]:
data.isnull().sum()

Age         0
Pclass      0
SibSp       0
Parch       0
Survived    0
dtype: int64

In [13]:
x = data.drop(columns=['Survived'])
y = data['Survived']

In [14]:
x.head()

    Age  Pclass  SibSp  Parch
0  34.5       3      0      0
1  47.0       3      1      0
2  62.0       2      0      0
3  27.0       3      0      0
4  22.0       3      1      1

In [15]:
y.head()

0    0
1    1
2    0
3    0
4    1
Name: Survived, dtype: int64

In [16]:
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression

In [19]:
cv = cross_val_score
lr = LogisticRegression()

In [20]:
# accuracy_score
np.mean(cross_val_score(lr,x,y,scoring='accuracy',cv=20))

np.float64(0.6238970588235293)

# Applying Feature construction

In [21]:
x['family_size'] = x['SibSp'] + x['Parch'] + 1

In [22]:
x.head()

    Age  Pclass  SibSp  Parch  family_size
0  34.5       3      0      0            1
1  47.0       3      1      0            2
2  62.0       2      0      0            1
3  27.0       3      0      0            1
4  22.0       3      1      1            3

In [25]:
# defining family size
def myfun(num):
    if(num == 1): # alone
        return 0
    elif (num > 2 & num < 4): # small family
        return 1
    else:
        return 2 # large_family

In [26]:
x['family_type'] =  x['family_size'].apply(myfun)

In [27]:
x.head()

    Age  Pclass  SibSp  Parch  family_size  family_type
0  34.5       3      0      0            1            0
1  47.0       3      1      0            2            2
2  62.0       2      0      0            1            0
3  27.0       3      0      0            1            0
4  22.0       3      1      1            3            1

In [29]:
x.drop(columns=['SibSp','Parch','family_size'])

      Age  Pclass  family_type
0    34.5       3            0
1    47.0       3            2
2    62.0       2            0
3    27.0       3            0
4    22.0       3            1
..    ...     ...          ...
409   3.0       3            1
411  37.0       1            2
412  28.0       3            0
414  39.0       1            0
415  38.5       3            0

[332 rows x 3 columns]

In [30]:
# prediction -> After feature construction
np.mean(cross_val_score(lr,x,y,scoring='accuracy',cv=20))

np.float64(0.6389705882352941)

# feature splitting

In [44]:
data.shape

(418, 12)

In [45]:
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [46]:
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [47]:
data['Name']

0                                  Kelly, Mr. James
1                  Wilkes, Mrs. James (Ellen Needs)
2                         Myles, Mr. Thomas Francis
3                                  Wirz, Mr. Albert
4      Hirvonen, Mrs. Alexander (Helga E Lindqvist)
                           ...
413                              Spector, Mr. Woolf
414                    Oliva y Ocana, Dona. Fermina
415                    Saether, Mr. Simon Sivertsen
416                             Ware, Mr. Frederick
417                        Peter, Master. Michael J
Name: Name, Length: 418, dtype: object

In [52]:
data['title'] = data['Name'].str.split(', ',expand=True)[1].str.split('.',expand=True)[0]

In [53]:
data['title']

0          Mr
1         Mrs
2          Mr
3          Mr
4         Mrs
        ...
413        Mr
414      Dona
415        Mr
416        Mr
417    Master
Name: title, Length: 418, dtype: object

In [56]:
data[['title','Name']]

      title                                          Name
0        Mr                              Kelly, Mr. James
1       Mrs              Wilkes, Mrs. James (Ellen Needs)
2        Mr                     Myles, Mr. Thomas Francis
3        Mr                              Wirz, Mr. Albert
4       Mrs  Hirvonen, Mrs. Alexander (Helga E Lindqvist)
..      ...                                           ...
413      Mr                            Spector, Mr. Woolf
414    Dona                  Oliva y Ocana, Dona. Fermina
415      Mr                  Saether, Mr. Simon Sivertsen
416      Mr                           Ware, Mr. Frederick
417  Master                      Peter, Master. Michael J

[418 rows x 2 columns]

In [62]:
# groping survival on behalf of their title
data.groupby('title').mean(numeric_only=True)['Survived'].sort_values(ascending=False)

title
Dona      1.0
Miss      1.0
Mrs       1.0
Ms        1.0
Col       0.0
Dr        0.0
Master    0.0
Mr        0.0
Rev       0.0
Name: Survived, dtype: float64